# This is a basic workflow that is manually triggered

name: Generate Changelog

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate:
    name: Generate Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Find Current Tag
        id: current
        uses: jimschubert/query-tag-action@v1
        with:
          include: 'v*'
          exclude: '*-rc*'
          commit-ish: '@'
          skip-unshallow: 'true'

      - name: Previous Tag
        id: last
        uses: jimschubert/query-tag-action@v1
        with:
          include: 'v*'
          exclude: ${{steps.current.outputs.tag}}
          skip-unshallow: 'true'

      - name: Generate changelog
        uses: jimschubert/beast-changelog-action@v1
        with:
          GITHUB_TOKEN: ${{github.token}}
          CONFIG_LOCATION: .github/changelog.json
          FROM: ${{steps.last.outputs.tag}}
          TO: ${{steps.current.outputs.tag}}
          OUTPUT: .github/CHANGELOG.md

      - name: Read CHANGELOG file
        id: getchangelog
        run: echo "::set-output name=changelog::$(cat .github/CHANGELOG.md)"

      - name: View Changelog
        run: cat .github/CHANGELOG.md

      - name: Add Artifact
        uses: actions/upload-artifact@v2
        with:
          name: out
          path: .github/CHANGELOG.md
      
  view:
    name: View Changelog Output
    runs-on: ubuntu-latest
    needs: [generate]
    steps:
      - name: Download Build Results
        uses: actions/download-artifact@v2
        with:
          name: out
          path: out

      - run: cat out/CHANGELOG.md
        
      # {needs.generate.outputs.changelog}}
