name: Gradle Tests and Nightly (CI)

on: push

jobs:
  vars:
    name: Get Variables
    runs-on: ubuntu-20.04
    outputs:
      release_type: ${{steps.cf_release_type.outputs.value }}
      mod_version: ${{steps.mod_version.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release Type
        id: cf_release_type
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'cf_release_type'

      - name: Mod Version
        id: mod_version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'mod_version'

  tests:
    name: Gradle Tests
    runs-on: ubuntu-20.04
    needs: [ vars ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: "8.0.282"

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test JAR with Gradle
        run: ./gradlew test
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  nightly:
    name: Publish Nightly
    runs-on: ubuntu-20.04
    needs: [ vars, tests ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: "8.0.282"

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish gradle nightly jar
        run: ./gradlew publishNightlyMavenPublicationToGitHubPackagesRepository
        env:
          CM_RELEASE: false
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}