name: Gradle Tests and Nightly (CI)

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - v*
    paths-ignore:
      - 'README.md'
      - LICENSE

jobs:
  vars:
    name: Get Variables
    runs-on: ubuntu-20.04
    outputs:
      release_type: ${{steps.cf_release_type.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        
      - name: Release Type
        id: cf_release_type
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'cf_release_type'

  tests:
    name: Gradle Tests
    runs-on: ubuntu-20.04
    needs: [ vars ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Unshallow and Get Tags
        run: git fetch --prune --unshallow --tags
        
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: "17"

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create datagen assets
        continue-on-error: true
        run: ./gradlew runData

      - name: Test JAR with GameTest Server
        run: ./gradlew runGameTestServer
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-data
          path: run/gametest

  nightly:
    name: Publish Nightly
    runs-on: ubuntu-20.04
    needs: [ vars, tests ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow and Get Tags
        run: git fetch --prune --unshallow --tags
        
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: "17"

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate Resources
        run: ./gradlew runData

      - name: Publish gradle nightly jar
        run: ./gradlew publishNightlyPublicationToGitHubPackagesRepository
        env:
          CM_RELEASE: false
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
