# Creates releases on Curseforge and Github Releases based on v* tags
name: Tagged Commit Release

on:
  workflow_dispatch:

jobs:
  vars:
    name: Gather Variables
    runs-on: ubuntu-20.04
    outputs:
      release_type: ${{steps.cf_release_type.outputs.value }}
      cf_project: ${{steps.cf_project.outputs.value }}
      mod_id: ${{steps.mod_id.outputs.value }}
      version: ${{steps.version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Release Type
        id: cf_release_type
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'cf_release_type'

      - name: Project ID
        id: cf_project
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'cf_project'

      - name: Mod ID
        id: mod_id
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'mod_id'

      - name: Find Current Tag
        id: current
        uses: jimschubert/query-tag-action@v1
        with:
          include: 'v*'
          exclude: '*-rc*'
          commit-ish: '@'
          skip-unshallow: 'true'

      - name: Semver Version
        id: version
        run: |
          version=$(echo "${{steps.current.outputs.tag}}" | cut -dv -f2)
          echo "::set-output name=version::$version"

  changelog:
    name: Generate Changelog (tags)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Find Current Tag
        id: current
        uses: jimschubert/query-tag-action@v1
        with:
          include: 'v*'
          exclude: '*-rc*'
          commit-ish: '@'
          skip-unshallow: 'true'

      - name: Previous Tag
        id: last
        uses: jimschubert/query-tag-action@v1
        with:
          include: 'v*'
          exclude: ${{steps.current.outputs.tag}}
          skip-unshallow: 'true'

      - name: Generate changelog
        uses: jimschubert/beast-changelog-action@v1
        with:
          GITHUB_TOKEN: ${{github.token}}
          CONFIG_LOCATION: .github/changelog.json
          FROM: ${{steps.last.outputs.tag}}
          TO: ${{steps.current.outputs.tag}}
          OUTPUT: .github/CHANGELOG.md

      - name: Read CHANGELOG file
        id: getchangelog
        run: echo "::set-output name=changelog::$(cat .github/CHANGELOG.md)"

      - name: View Changelog
        run: cat .github/CHANGELOG.md

      - name: Add Artifact
        uses: actions/upload-artifact@v2
        with:
          name: out
          path: .github/CHANGELOG.md

  jar:
    name: Publish JAR
    runs-on: ubuntu-20.04
    needs: [vars, changelog]
    steps:
      - name: Download Changelog Results
        uses: actions/download-artifact@v2
        with:
          name: out
          path: changelog

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: "17"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create datagen assets
        run: ./gradlew runData
        timeout-minutes: 15
        env:
          CM_RELEASE: true
          
      - name: Test JAR with GameTest Server
        run: ./gradlew runGameTestServer
        timeout-minutes: 20
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-data
          path: run/gametest

      - name: Build JAR
        run: ./gradlew build
        timeout-minutes: 10
        env:
          CM_RELEASE: true
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Artifact
        uses: actions/upload-artifact@v2
        with:
          name: libs
          path: |
            build-out/${{ needs.vars.outputs.mod_id }}-${{ needs.vars.outputs.version }}.jar
            build-out/${{ needs.vars.outputs.mod_id }}-${{ needs.vars.outputs.version }}-api.jar

  view:
    name: View Changelog Output
    runs-on: ubuntu-20.04
    needs: [changelog]
    steps:
      - name: Download Build Results
        uses: actions/download-artifact@v2
        with:
          name: out
          path: changelog
      - run: cat changelog/CHANGELOG.md

  release:
    name: Make Releases
    runs-on: ubuntu-20.04
    needs: [changelog, vars, jar]
    steps:
      - name: Download Build Results
        uses: actions/download-artifact@v2
        with:
          name: libs
          path: build-out
      - name: Download Changelog Results
        uses: actions/download-artifact@v2
        with:
          name: out
          path: changelog

      - name: Load Changelog File
        id: changelog
        run: echo ::set-output name=changelog::$(cat changelog/CHANGELOG.md)

      - name: Create GitHub Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          title: "Release ${{ github.event.release.tag_name }}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            changelog/CHANGELOG.md
            build-out/${{ needs.vars.outputs.mod_id }}-${{ needs.vars.outputs.version }}.jar
            build-out/${{ needs.vars.outputs.mod_id }}-${{ needs.vars.outputs.version }}-api.jar

      - name: Full File
        id: filename
        run: echo "::set-output name=fullpath::build-out/${{ needs.vars.outputs.mod_id }}-${{ needs.vars.outputs.version }}.jar"

      - name: Create CurseForge Release
        uses: itsmeow/curseforge-upload@master
        with:
          token: ${{ secrets.CF_API_TOKEN }}
          project_id: ${{ needs.vars.outputs.cf_project }}
          game_endpoint: minecraft
          file_path: ${{ steps.filename.outputs.fullpath }}
          changelog: ${{ steps.changelog.outputs.changelog }}
          changelog_type: markdown
          game_versions: java:Java 17,Forge
          release_type: ${{ needs.vars.outputs.release_type }}

  publishMaven:
    name: Maven Release (GH Packages)
    runs-on: ubuntu-20.04
    needs: [changelog, vars, jar]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: "17"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate Resources
        run: ./gradlew runData

      - name: Publish gradle nightly jar
        run: ./gradlew publishReleasePublicationToGitHubPackagesRepository
        env:
          CM_RELEASE: true
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
